// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGi6JM6zoXFHHxs8w52Zewh46PuBIdrp4',
    appId: '1:292095507245:android:816484c998736370a271a4',
    messagingSenderId: '292095507245',
    projectId: 'bushier2',
    databaseURL: 'https://bushier2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bushier2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4r83891n0hdMft4ltxboGQbdQGUvjd8',
    appId: '1:292095507245:ios:dc8a98968156ff33a271a4',
    messagingSenderId: '292095507245',
    projectId: 'bushier2',
    databaseURL: 'https://bushier2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bushier2.appspot.com',
    iosClientId: '292095507245-7o4vqob7hk4o9tugstt5p4e311dmtnl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bushier2',
  );
}
